export const ADD_COMMENT="ADD_COMMENTS";
export const ADD_COURSES="ADD_COURSES";

export const SHOW_COURSES="SHOW_COURSES";
export const FAILED_COURSES="FAILED_COURSES";
export const LOADING_COURSES="LOADING_COURSES";
