export const ADD_COMMENT="ADD_COMMENTS";
export const ADD_COURSES="ADD_COURSES";

export const SHOW_COURSES="SHOW_COURSES";
export const FAILED_COURSES="FAILED_COURSES";
export const LOADING_COURSES="LOADING_COURSES";


export const SHOW_COMMENTS="SHOW_COMMENTS";
export const FAILED_COMMENTS="FAILED_COMMENTS";
export const LOADING_COMMENTS="LOADING_COMMENTS";
