export const ADD_COMMENT="ADD_COMMENTS";
export const ADD_COURSES="ADD_COURSES";

export const SHOW_COURSES="SHOW_COURSES";
export const FAILED_COURSES="FAILED_COURSES";
export const LOADING_COURSES="LOADING_COURSES";

export const SHOW_USERS="SHOW_USERS";
export const FAILED_USERS="FAILED_USERS";
export const LOADING_USERS="LOADING_USERS";
export const SHOW_USER="SHOW_USER";
export const FAILED_USER="FAILED_USER";
export const LOADING_USER="LOADING_USER";

export const LOADING_UPDATED_USERS="LOADING_UPDATED_USERS";
export const FAILED_UPDATED_USERS="FAILED_UPDATED_USERS";
export const SHOW_UPDATED_USERS="SHOW_UPDATED_USERS";


export const SHOW_COMMENTS="SHOW_COMMENTS";
export const FAILED_COMMENTS="FAILED_COMMENTS";
export const LOADING_COMMENTS="LOADING_COMMENTS";


export const REQUEST_LOGIN="REQUEST_LOGIN";
export const REQUEST_SUCCESS="REQUEST_SUCCESS";
export const FAILED_LOGIN="FAILED_LOGIN";

export const REQUEST_LOGOUT="REQUEST_LOGOUT";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";

